# Job para Configuração Inicial do RabbitMQ
# Executa após o RabbitMQ estar pronto para configurar filas e permissões

apiVersion: batch/v1
kind: Job
metadata:
  name: rabbitmq-setup
  namespace: default
  labels:
    app: rabbitmq-setup
spec:
  ttlSecondsAfterFinished: 300  # Remove job após 5 minutos de conclusão
  template:
    metadata:
      labels:
        app: rabbitmq-setup
    spec:
      restartPolicy: OnFailure
      containers:
      - name: rabbitmq-setup
        image: rabbitmq:3.12-management
        command:
        - /bin/bash
        - -c
        - |
          echo "🚀 Iniciando configuração do RabbitMQ..."
          
          # Função para aguardar RabbitMQ estar pronto
          wait_for_rabbitmq() {
            local max_attempts=20
            local attempt=1
            
            while [ $attempt -le $max_attempts ]; do
              echo "⏳ Tentativa $attempt/$max_attempts - Verificando RabbitMQ..."
              
              # Descobrir o nome do pod RabbitMQ
              RABBITMQ_POD=$(kubectl get pods -l app=rabbitmq -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)
              if [ -z "$RABBITMQ_POD" ]; then
                echo "⚠️ Pod RabbitMQ não encontrado, aguardando 10s..."
                sleep 10
                attempt=$((attempt + 1))
                continue
              fi
              
              # Testar ping no pod específico
              if rabbitmq-diagnostics -n rabbit@$RABBITMQ_POD ping > /dev/null 2>&1; then
                echo "✅ RabbitMQ está respondendo no pod: $RABBITMQ_POD"
                export RABBITMQ_POD
                return 0
              fi
              
              echo "⚠️ RabbitMQ ainda não está pronto, aguardando 10s..."
              sleep 10
              attempt=$((attempt + 1))
            done
            
            echo "❌ Timeout aguardando RabbitMQ após $((max_attempts * 10))s"
            return 1
          }
          
          # Aguardar RabbitMQ estar pronto
          if ! wait_for_rabbitmq; then
            echo "❌ Falha ao conectar com RabbitMQ"
            exit 1
          fi
          
          echo "🔧 Configurando loopback_users no pod: $RABBITMQ_POD..."
          # Configurar loopback users para permitir conexões remotas do guest
          if rabbitmqctl -n rabbit@$RABBITMQ_POD eval 'application:set_env(rabbit, loopback_users, []).'; then
            echo "✅ Configuração loopback_users aplicada com sucesso"
          else
            echo "⚠️ Falha ao configurar loopback_users (pode já estar configurado)"
          fi
          
          echo "📋 Criando filas necessárias..."
          
          # Criar filas para Azure Functions
          queues=("pne-email" "pne-integracao-rota" "pne-integracao-arquivo")
          
          for queue in "${queues[@]}"; do
            echo "📦 Criando fila: $queue"
            if rabbitmqadmin -H rabbitmq-service declare queue name="$queue" durable=true; then
              echo "✅ Fila $queue criada com sucesso"
            else
              echo "⚠️ Fila $queue pode já existir ou houve erro"
            fi
          done
          
          echo "📊 Verificando status final..."
          
          # Verificar filas criadas
          echo "📋 Listando filas:"
          rabbitmqctl -n rabbit@$RABBITMQ_POD list_queues name messages
          
          # Verificar configuração loopback
          echo "🔍 Verificando configuração loopback:"
          rabbitmqctl -n rabbit@$RABBITMQ_POD eval 'application:get_env(rabbit, loopback_users).'
          
          echo "🎉 Configuração do RabbitMQ concluída com sucesso!"
          
        env:
        - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
          value: "-rabbit loopback_users []"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      # Aguardar até 10 minutos para o job completar
      activeDeadlineSeconds: 600