apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.ports.amqp.port }}
          name: amqp
        - containerPort: {{ .Values.service.ports.management.port }}
          name: management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.credentials.username | quote }}
        - name: RABBITMQ_DEFAULT_PASS
          value: {{ .Values.credentials.password | quote }}
        - name: RABBITMQ_ERLANG_COOKIE
          value: {{ .Values.credentials.erlangCookie | quote }}
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
        - name: rabbitmq-config-volume
          mountPath: /etc/rabbitmq/rabbitmq.conf
          subPath: rabbitmq.conf
        - name: rabbitmq-config-volume
          mountPath: /etc/rabbitmq/enabled_plugins
          subPath: enabled_plugins
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory | quote }}
            cpu: {{ .Values.resources.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.limits.memory | quote }}
            cpu: {{ .Values.resources.limits.cpu | quote }}
        livenessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - ping
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - check_port_connectivity
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: rabbitmq-data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: rabbitmq-pvc
        {{- end }}
      - name: rabbitmq-config-volume
        configMap:
          name: rabbitmq-config
