# Exemplo ScaledObject - Memory Autoscaling
# Este exemplo escala baseado no uso de memoria
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: memory-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: memory-app-deployment
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: memory
    metadata:
      type: Utilization
      value: "80"  # Escala quando Memory > 80%
---
# Deployment de exemplo com uso de memoria
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-app-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: memory-app
  template:
    metadata:
      labels:
        app: memory-app
    spec:
      containers:
      - name: memory-app
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 512Mi