apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    app: redis
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    tcp-keepalive 300
    databases 16
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    save 900 1
    save 300 10
    save 60 10000
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    dir /data
    {{- if .Values.auth.enabled }}
    requirepass {{ .Values.auth.password }}
    {{- end }}