apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: redis
    port: {{ .Values.service.ports.redis.port }}
    targetPort: 6379
    nodePort: {{ .Values.service.ports.redis.nodePort }}
  selector:
    app: redis