apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: default
data:
  rabbitmq.conf: |
    # Configurações básicas
    default_user = guest
    default_pass = guest
    default_vhost = /
    
    # Permissões padrão
    default_permissions.configure = .*
    default_permissions.read = .*
    default_permissions.write = .*
    
    # CORREÇÃO: Permitir conexões remotas para guest (Azure Functions)
    loopback_users = none
    
    # Configurações de performance
    vm_memory_high_watermark.relative = 0.6
    disk_free_limit.relative = 1.0
    
    # Configurações de rede
    listeners.tcp.default = 5672
    management.tcp.port = 15672
    
    # Logs
    log.console = true
    log.console.level = info
    log.file = false
    
    # Configurações de cluster (para futuro)
    cluster_formation.peer_discovery_backend = classic_config
    
    # Configurações de heartbeat
    heartbeat = 60
    
  enabled_plugins: |
    [rabbitmq_management,rabbitmq_prometheus,rabbitmq_management_agent].
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: default
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.12-management
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"
        - name: RABBITMQ_DEFAULT_PASS
          value: "guest"
        - name: RABBITMQ_ERLANG_COOKIE
          value: "SWQOKODSQALRPCLNMEQG"
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
        - name: rabbitmq-config-volume
          mountPath: /etc/rabbitmq/rabbitmq.conf
          subPath: rabbitmq.conf
        - name: rabbitmq-config-volume
          mountPath: /etc/rabbitmq/enabled_plugins
          subPath: enabled_plugins
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - ping
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - check_port_connectivity
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: rabbitmq-pvc
      - name: rabbitmq-config-volume
        configMap:
          name: rabbitmq-config
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq
spec:
  type: NodePort
  ports:
  - port: 5672
    targetPort: 5672
    name: amqp
    nodePort: 30672
  - port: 15672
    targetPort: 15672
    name: management
    nodePort: 31672
  selector:
    app: rabbitmq