apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: {{ .Values.credentials.username | b64enc | quote }}
  password: {{ .Values.credentials.password | b64enc | quote }}
